import { Router, type IRouter } from "express";
import healthRouter from "./health";
import articlesRouter from "./articles";
import topicsRouter from "./topics";
import seriesRouter from "./series";
import searchRouter from "./search";
import newsletterRouter from "./newsletter";
import authRouter from "./auth";
import bookmarksRouter from "./bookmarks";
import likesRouter from "./likes";
import commentsRouter from "./comments";
import dashboardRouter from "./dashboard";
import resourcesRouter from "./resources";
import founderStoriesRouter from "./founder-stories";
import communityRouter from "./community";
import adminRouter from "./admin";
import paymentsRouter from "./payments";
import cmsRouter from "./cms";
import aiRouter from "./ai";
import notificationsRouter from "./notifications";
import followedTopicsRouter from "./followed-topics";
import pandaLabsRouter from "./panda-labs";
import mentorshipRouter from "./mentorship";

const router: IRouter = Router();

router.use(healthRouter);
router.use(articlesRouter);
router.use(topicsRouter);
router.use(seriesRouter);
router.use(searchRouter);
router.use(newsletterRouter);
router.use(authRouter);
router.use(bookmarksRouter);
router.use(likesRouter);
router.use(commentsRouter);
router.use(dashboardRouter);
router.use(resourcesRouter);
router.use(founderStoriesRouter);
router.use(communityRouter);
router.use(adminRouter);
router.use(paymentsRouter);
router.use(cmsRouter);
router.use(aiRouter);
router.use(notificationsRouter);
router.use(followedTopicsRouter);
router.use(pandaLabsRouter);
router.use(mentorshipRouter);

export default router;
